name: Benchmarks

on:
  push:
    branches: [main]

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate benchmark plots
        run: |
          python scripts/benchmark.py --num-examples 8 --num-samples 64 --batch-size 4 --output-dir benchmarks
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-plots
          path: benchmarks
